version: "3.9"

services:
  postgres:
    container_name: db
    image: postgres
    env_file:
      - .env
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - fastapi-piccolo-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  fastapi:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - $FAST_API_PORT:$FAST_API_PORT
    env_file:
      - .env
    volumes:
      - ./home:/app/home
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    restart: on-failure:5

volumes:
  fastapi-piccolo-db:
